---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  strategy: debug
  vars_files:
    - config_vars/{{ instance_type }}
  gather_facts: False
  tasks:

  - name: Get public IP address for this computer
    ipify_facts:
    register: my_public_ip

  - name: Create a security group
    ec2_group:
      name: ansible
      description: "Ansible Security Group"
      region: "{{ aws_region }}"
      #vpc_id: "{{ vpc_id }}"
      # aws_access_key: # Uses environment variable $AWS_ACCESS_KEY_ID
      # aws_secret_key: # Uses environment variable $AWS_SECRET_ACCESS_KEY
      rules:
        - proto: all
          cidr_ip: "{{ ipify_public_ip + '/32' }}"
        - proto: all
          group_name: ansible
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall

  - name: Create an EC2 instance
    ec2:
      # aws_access_key: # Uses environment variable $AWS_ACCESS_KEY_ID
      # aws_secret_key: # Uses environment variable $AWS_SECRET_ACCESS_KEY
      key_name: "{{ ssh_key_name }}"
      region: "{{ aws_region }}"
      zone:  #"{{ aws_zone }}"
      group_id: "{{ firewall.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      #volumes:
      #  - device_name: /dev/xvdf
      #    snapshot: snap-09140a5b20956af9f
      #    volume_size: 100
      #    volume_type: gp2
      #    delete_on_termination: true
      exact_count: 1
      spot_price: "{{ spot_price }}"
      count_tag:
         Name: deep-learning
      instance_tags:
         Name: deep-learning
    register: ec2

  - debug: msg="DNS {{ item.dns_name }}"
    with_items: "{{ ec2.instances }}"

  - name: Create SSH Group to login dynamically to EC2 Instance
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: ec2_server
    with_items: "{{ ec2.instances }}"

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"
